apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient-deployment
  template:
    metadata:
      labels:
        app: patient-deployment
    spec:
      containers:
        - name: patient-deployment
          image: aishwaryakr/patient-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5244
          env:
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_CONN
            - name: ConnectionStrings__RedisConnection
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: REDIS_CONN
            - name: Jwt__Key
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: JWT_SECRET
            - name: Kafka__BootstrapServers
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: KAFKA_BOOTSTRAP_SERVERS
 