apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: patientdb
  DB_CONN: Host=postgres-service;Port=5432;Database=patientdb;Username=postgres;Password=postgres
  JWT_SECRET: ThisIsASecretKeyForJwtTokenGeneration